import type { Metadata } from "next";
import "@/styles/globals.css";
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`overflow-x-hidden`}
      >
        <NextTopLoader
          color="#F7931A"
        />
        <Toaster
          position="top-center"
          reverseOrder={false}
        />

        <div
          id="scale-wrapper"
          className="w-[1280px] mx-auto"
          style={{
            transform: 'scale(calc(100vw / 1280))',
            transformOrigin: 'top left',
            height: '100vh',
            overflow: 'hidden',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
