-- moreBTC 左側目錄：把原本寫死在 src/config/MoreInfo.json 的分類搬進資料庫，
-- 讓後台可以直接編輯。
--
-- posts 格式：[{ "title": string, "filename": string }]
--   filename 不含 .md，對應 Post.filename 去掉副檔名

create table if not exists public."MoreInfo" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  label text,
  title text not null,
  folder text not null default 'KnowBTC',
  sort_order integer not null default 0,
  posts jsonb not null default '[]'::jsonb
);

alter table public."MoreInfo"
  drop constraint if exists "MoreInfo_posts_is_array";
alter table public."MoreInfo"
  add constraint "MoreInfo_posts_is_array"
  check (jsonb_typeof(posts) = 'array');

create index if not exists "MoreInfo_sort_order_idx"
  on public."MoreInfo" (sort_order);

-- 前台用 anon key 讀，後台用登入身分寫
alter table public."MoreInfo" enable row level security;

drop policy if exists "MoreInfo select for all" on public."MoreInfo";
create policy "MoreInfo select for all"
  on public."MoreInfo" for select
  using (true);

drop policy if exists "MoreInfo write for authenticated" on public."MoreInfo";
create policy "MoreInfo write for authenticated"
  on public."MoreInfo" for all
  to authenticated
  using (true)
  with check (true);

-- 把現有 MoreInfo.json 的內容搬進來（只在表是空的時候跑）
insert into public."MoreInfo" (label, title, folder, sort_order, posts)
select * from (values
  (null, '認識比特幣', 'KnowBTC', 0, '[{"title": "比特幣 Bitcoin", "filename": "about"}, {"title": "比特幣 基本資訊", "filename": "2024090823"}, {"title": "中本聰", "filename": "2024090831"}, {"title": "比特幣 錢包", "filename": "Wallet"}, {"title": "購買 比特幣", "filename": "Buy"}, {"title": "比特幣 區塊鏈瀏覽器 簡介", "filename": "2024090806"}, {"title": "比特幣 發行機制", "filename": "2024090804"}, {"title": "比特幣 分叉", "filename": "2024090801"}, {"title": "比特幣 起源 背景", "filename": "2024090820"}]'::jsonb),
  (null, '比特幣故事', 'KnowBTC', 1, '[{"title": "Pizza Day 社群第一次比特幣採用", "filename": "2024090816"}, {"title": "HODL", "filename": "2024090821"}, {"title": "BUIDL", "filename": "2024090825"}]'::jsonb),
  ('比特幣技術資訊', '演算法', 'KnowBTC', 2, '[{"title": "安全雜湊演算法 SHA256  簡介", "filename": "2024090812"}, {"title": "橢圓曲線數字簽名算法 ECDSA  簡介", "filename": "2024090813"}]'::jsonb),
  (null, 'BIP 比特幣 改進提案', 'KnowBTC', 3, '[{"title": "BIP 比特幣 改進提案", "filename": "2024090827"}, {"title": "BIP 39", "filename": "2024090828"}]'::jsonb),
  (null, '其他技術', 'KnowBTC', 4, '[{"title": "隔離見證 Segwit 簡介", "filename": "2024090815"}, {"title": "閃電網路 Lighting Network 簡介", "filename": "2024090810"}]'::jsonb)
) as seed(label, title, folder, sort_order, posts)
where not exists (select 1 from public."MoreInfo");
